# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ailin Hernandez
email: ailin10@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ailin Hernandez. Frontend Developer. Love HCI, UX & A11y.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ailin10.github.io/" # the base hostname & protocol for your site
twitter_username: ailin10
github_username:  ailin10

# Build settings
markdown: kramdown
sass:
  style: compressed
